# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: purple

# SEO
marketing:
  seo:
    site_type: Project
    local_business_type: ''
    org_name: ''
    description: 'Thư Viện Hoằng Pháp.'
    twitter: 'tienthieusac'
  analytics:
    google_analytics: 'G-K848VVTHBW'
    google_tag_manager: ''
    microsoft_clarity: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: ""
      # Logo filename in `assets/media/` folder
      filename: "logo.png"
    button:
      enable: true
      text: "Bắt đầu"
      url: "https://thuvienhoangphap.github.io/docs/"
    show_search: true
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice: '© {year} Thư Viện Hoằng Pháp. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/thuvienhoangphap/thuvienhoangphap.github.io'
    content_dir: 'content'
    branch: 'main'
  feedback:
    responses:
      positive: 'Glad to hear it! [Any ideas for improvements?](https://github.com/thuvienhoangphap/thuvienhoangphap.github.io/issues/new).'
      negative: 'Sorry to hear that. [Please tell us how we can improve](https://github.com/thuvienhoangphap/thuvienhoangphap.github.io/issues/new).'
  comment:
    provider: 'giscus'
    giscus:
      repo: 'thuvienhoangphap/thuvienhoangphap.github.io'
      repo_id: 'R_kgDOLvzwRA'
      category: 'Announcements'
      category_id: 'DIC_kwDOLvzwRM4CfGKK'
